name: TestInDocker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container: ghcr.io/danielme85/lltdb-testbench:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Start containers
        run: docker-compose up -d mariadb mongo

      - name: Install composer packages
        run:  cd /var/testing && composer install --no-interaction

      - name: Run tests
        run: cd /var/testing && dockerize -wait tcp://mariadb:3306 -timeout 1m && ./vendor/bin/testbench package:test

      - name: Cleanup containers
        run: docker-compose down

