name: RunPhpUnitInDocker

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  docker:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Start containers
        run: docker-compose up -d mariadb mongo

      - name: Start test container
        run: docker-compose up php8

      - name: Cleanup containers
        run: docker-compose down
